### ISSUE TITLE
missing models

### ISSUE THREAD

**Issue by Shubbair** [niconielsen32/ComputerVision#9]

**Comment by niconielsen32** [comment]
What models are u missing?

**Comment by Shubbair** [comment]
sorry I was looking for the models and finally found it , thanks :)

**Comment by Divyanshu-BlueBricks** [comment]
Hey, Im also looking for the model file model-f6b98070.onnx. Where did u find it?

**Comment by hakkirah** [comment]
> 

https://github.com/isl-org/MiDaS/releases/download/v2_1/model-f6b98070.onnx
